# deployment.yaml file

apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-war-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-war
  template:
    metadata:
      labels:
        app: java-war
    spec:
      containers:
        - name: java-war
          image: gunnapradeepreddy/java-war-app:v1
          ports:
            - containerPort: 8080

